version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: votre-username/bde-events-api:v1
    container_name: bde_events_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=bde_events
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: votre-username/bde-events-react:v1
    container_name: bde_events_react
    ports:
      - "8080:8080"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api

  db:
    image: mysql:8.0
    container_name: bde_events_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bde_events
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: